### PR TITLE
bump to preshed 2.0.1

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Same exercise as conda-forge/cymem-feedstock#6, closes #6 #7

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by h-vetinari** [comment]
@rmax @scopatz @jjhelmus PTAL

**Comment by scopatz** [comment]
Thanks for opening this, let's see if @rmax gets to this in the next day

**Comment by h-vetinari** [comment]
@scopatz
This should be done...

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
The rerender failed locally as well (cf. conda-forge/conda-smithy#1107), but left the updated content as unstaged changes. This is what I committed in https://github.com/conda-forge/preshed-feedstock/pull/8/commits/0f67f688e00698206549373c4f9eceeef43c5461.

Aside from a new `LICENCE` file, the main changes of the rerender were changes in file permissions:
```
>git diff 6e0f876643bc8d0ed2d531e0059a6772ded993ee
diff --git a/.azure-pipelines/azure-pipelines-linux.yml b/.azure-pipelines/azure-pipelines-linux.yml
old mode 100755
new mode 100644
diff --git a/.azure-pipelines/azure-pipelines-osx.yml b/.azure-pipelines/azure-pipelines-osx.yml
old mode 100755
new mode 100644
diff --git a/.azure-pipelines/azure-pipelines-win.yml b/.azure-pipelines/azure-pipelines-win.yml
old mode 100755
new mode 100644
diff --git a/.azure-pipelines/build_steps.sh b/.azure-pipelines/build_steps.sh
old mode 100755
new mode 100644
diff --git a/.azure-pipelines/run_docker_build.sh b/.azure-pipelines/run_docker_build.sh
old mode 100755
new mode 100644
diff --git a/LICENSE b/LICENSE
new file mode 100644
index 0000000..e69de29
diff --git a/build-locally.py b/build-locally.py
old mode 100755
new mode 100644
```

This seems like it was too eager, as now the linux agent on azure cannot execute the script:
```
.azure-pipelines/run_docker_build.sh: Permission denied
```

@conda-forge/core

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@scopatz
OK, this is back to functional, and the rerender [says](https://github.com/conda-forge/preshed-feedstock/pull/8#issuecomment-511298022) it's at the most current state.

Seems the conda smithy was fixed since I tried the last rerender. :)

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
