### PR TITLE
Update for v3.0.9

### PR DESCRIPTION
**Pull request by adrianeboyd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by adrianeboyd** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
We shouldn't go back from 4.0.0 to 3.0.9, but if you want we can create a 3.x branch and then point this PR there.

**Review by h-vetinari — CHANGES_REQUESTED** [review]
See comment

**Comment by adrianeboyd** [comment]
Wait a minute, I did this intentionally because I don't want this on a branch. I want this to go back to using v3.x as the current release and be able to have bot-generated PR updates for new releases for v3.x.

Or I guess I'm okay with a branch if you can enable bot-generated PR updates for the branch. I mainly don't want to have to do this manually for future releases, since it's easy to overlook. (This seems to be a general problem if you're actively maintaining multiple release branches for a package? Or possibly I just don't know how to configure it correctly here?)

v4.0.0 was yanked on pypi (a while ago ... in April, I think?) and we want to go back to v3.x as the current release on conda-forge, too. There has been enough of a delay that I am not sure what the best way is to effectively remove the preshed v4.0.0 release from conda-forge, though, since the procedures are so different.

**Comment by h-vetinari** [comment]
> v4.0.0 was yanked on pypi (a while ago ... in April, I think?) and we want to go back to v3.x as the current release on conda-forge

That would have been relevant context. The package should have been yanked on conda-forge there and then as well, but now that it's been live for 5 months, that's less great. The only silver lining is that there haven't been too many [downloads](https://anaconda.org/conda-forge/preshed/files) of 4.0, so I guess we could still do it if necessary.

Marking 4.0 as broken is kinda the only way that makes sense for going back to 3.0.9 on the main branch; otherwise, consumers of unpinned `preshed` will always get 4.0 because it's "newer" from the PoV of the version number.

It's an unusual situation to unpublish a major version. Is there not going to be a 4.0 in the future at all? In any case, it would be possible to make much of the automation (minus the automated version updates) work also for a `v3.x` branch, but if you're abandoning 4.0 for the foreseeable future, then let's delete that branch and direct this PR to main.

PS. You might be used to knowing what's necessary to do for a given package, but not providing relevant context on your PRs to the feedstock makes it very hard to determine what's going on. Sorry for messing up your PR.

**Comment by adrianeboyd** [comment]
It was a mistake to have released this as v4.0.0 rather than v4.0.0.dev0, and a mistake to have let it be merged here before we'd done further testing.

The explosion libraries (spacy, thinc, etc.) are basically the only users of the package, and none of our downstream packages have been updated to allow v4.0 because we discovered bugs once we started testing the release further downstream on our end.

We're short on resources right now to debug v4.0, so I think it would be better to go back to v3.x on `main`. Let me see give that a shot...

I don't really know what to do about the older v4.0.0 conda-forge release. It doesn't cause any major problems on end to have it remain available given the longer history, but if you think I should get it marked as broken I can see about doing that.

**Comment by h-vetinari** [comment]
I deleted the v3.x branch again. Note that a lot of the automation (like the automated PRs for new versions) will not work anymore until the preshed version is larger than 4.0.0 again (because the bot will see a new tag and compare `${new}>${old}`, where old=4.0.0, and only open a PR if the condition evaluates to true).

**Pull request closed without merging**
